CREATE TABLE RiskAssessmentLogs (
    LogID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RequestJSON TEXT,
    ResponseJSON TEXT,
    Status VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RiskAssessments (
    AssessmentID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LogID INTEGER,
    RecordID VARCHAR(50),
    OverallRiskScore INTEGER,
    InitialRiskLevel VARCHAR(50),
    OverallRiskLevel VARCHAR(50),
    TypeOfLogicApplied VARCHAR(100),
    SmeRiskAssessment VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LogID) REFERENCES RiskAssessmentLogs(LogID)
);

CREATE TABLE RiskAssessmentDetails (
    DetailID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssessmentID INTEGER,
    RiskType VARCHAR(50),
    ElementName VARCHAR(100),
    ElementValue VARCHAR(255),
    RiskScore INTEGER,
    Flag VARCHAR(10),
    LocalRuleApplied VARCHAR(10),
    FOREIGN KEY (AssessmentID) REFERENCES RiskAssessments(AssessmentID)
);

CREATE TABLE RiskMappings (
    MappingID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TargetPath VARCHAR(255) NOT NULL,
    SourceField VARCHAR(100),
    DefaultValue VARCHAR(255),
    Category VARCHAR(100)
);
