CREATE TABLE IF NOT EXISTS RiskAssessmentLogs (
    LogID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RequestJSON  TEXT,
    ResponseJSON TEXT,
    Status       VARCHAR(50),
    CreatedAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RiskAssessments (
    AssessmentID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LogID               BIGINT,
    RecordID            VARCHAR(50),
    OverallRiskScore    INTEGER,
    InitialRiskLevel    VARCHAR(50),
    OverallRiskLevel    VARCHAR(50),
    TypeOfLogicApplied  VARCHAR(100),
    SmeRiskAssessment   VARCHAR(50),
    CreatedAt           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LogID) REFERENCES RiskAssessmentLogs(LogID)
);

CREATE TABLE IF NOT EXISTS RiskAssessmentDetails (
    DetailID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssessmentID     BIGINT,
    RiskType         VARCHAR(50),
    ElementName      VARCHAR(100),
    ElementValue     VARCHAR(255),
    RiskScore        INTEGER,
    Flag             VARCHAR(10),
    LocalRuleApplied VARCHAR(10),
    FOREIGN KEY (AssessmentID) REFERENCES RiskAssessments(AssessmentID)
);

CREATE TABLE IF NOT EXISTS RiskMappings (
    MappingID    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TargetPath   VARCHAR(255) NOT NULL,
    SourceField  VARCHAR(100),
    DefaultValue VARCHAR(255),
    Category     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS BatchRuns (
    BatchID            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BatchName          VARCHAR(255) NOT NULL,
    RunStatus          VARCHAR(50),  -- INITIATED, UPLOADED, FAILED
    NotificationStatus VARCHAR(50),
    FeedbackCount      INT,
    CreatedAt          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
