CREATE TABLE IF NOT EXISTS AppUsers (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    Enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS RolePermissions (
    RoleName VARCHAR(50) NOT NULL,
    Permission VARCHAR(100) NOT NULL,
    PRIMARY KEY (RoleName, Permission)
);

CREATE TABLE IF NOT EXISTS UserAudits (
    AuditID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID BIGINT,
    Username VARCHAR(50),
    Action VARCHAR(100),
    Details TEXT,
    IPAddress VARCHAR(50),
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    -- FOREIGN KEY (UserID) REFERENCES AppUsers(UserID) -- Optional: enforce valid user if needed
);

-- Seed Data (Optional, but good for dev)
MERGE INTO AppUsers (Username, Password, Role, Enabled) KEY (Username) VALUES ('admin', '{noop}admin', 'ADMIN', TRUE);
MERGE INTO AppUsers (Username, Password, Role, Enabled) KEY (Username) VALUES ('user', '{noop}user', 'USER', TRUE);
MERGE INTO AppUsers (Username, Password, Role, Enabled) KEY (Username) VALUES ('analyst', '{noop}password', 'KYC_ANALYST', TRUE);
MERGE INTO AppUsers (Username, Password, Role, Enabled) KEY (Username) VALUES ('reviewer', '{noop}password', 'KYC_REVIEWER', TRUE);
MERGE INTO AppUsers (Username, Password, Role, Enabled) KEY (Username) VALUES ('afc_user', '{noop}password', 'AFC_REVIEWER', TRUE);
MERGE INTO AppUsers (Username, Password, Role, Enabled) KEY (Username) VALUES ('aco_user', '{noop}password', 'ACO_REVIEWER', TRUE);

-- Seed Permissions for Admin
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ADMIN', 'MANAGE_USERS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ADMIN', 'MANAGE_PERMISSIONS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ADMIN', 'VIEW_CLIENTS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ADMIN', 'EDIT_CLIENTS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ADMIN', 'VIEW_SENSITIVE_DATA');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ADMIN', 'MANAGE_CASES');

-- Seed Permissions for Analyst
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('KYC_ANALYST', 'VIEW_CLIENTS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('KYC_ANALYST', 'MANAGE_CASES');

-- Seed Permissions for Reviewer
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('KYC_REVIEWER', 'VIEW_CLIENTS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('KYC_REVIEWER', 'MANAGE_CASES');

-- Seed Permissions for AFC
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('AFC_REVIEWER', 'VIEW_CLIENTS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('AFC_REVIEWER', 'MANAGE_CASES');

-- Seed Permissions for ACO
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ACO_REVIEWER', 'VIEW_CLIENTS');
MERGE INTO RolePermissions (RoleName, Permission) KEY (RoleName, Permission) VALUES ('ACO_REVIEWER', 'MANAGE_CASES');
