server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: risk-service
          uri: lb://risk-service
          predicates:
            - Path=/api/risk/**
          filters:
            - RewritePath=/api/risk/(?<remaining>.*), /api/internal/risk/${remaining}
        - id: screening-service-batch
          uri: lb://screening-service
          predicates:
            - Path=/api/internal/screening/**
        - id: auth-service-login
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**, /api/permissions/**
        - id: core-viewer
          uri: lb://viewer-core
          predicates:
            - Path=/api/**, /login, /logout, /
        - id: core-viewer-catchall
          uri: lb://viewer-core
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
    hostname: ${HOSTNAME:localhost}
