CREATE TABLE IF NOT EXISTS ScreeningLogs (
    LogID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT, -- No FK constraint as Client table is in another service
    RequestPayload TEXT, -- H2 compatible
    ResponsePayload TEXT,
    OverallStatus VARCHAR(50),
    ExternalRequestID VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ScreeningResults (
    ResultID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ScreeningLogID BIGINT,
    ContextType VARCHAR(50), -- PEP, ADM, INT, SAN
    Status VARCHAR(50), -- HIT, NO_HIT, IN_PROGRESS
    AlertStatus VARCHAR(50),
    AlertMessage TEXT,
    AlertID VARCHAR(100),
    FOREIGN KEY (ScreeningLogID) REFERENCES ScreeningLogs(LogID)
);

CREATE TABLE IF NOT EXISTS BatchRuns (
    BatchID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BatchName VARCHAR(255) NOT NULL,
    RunStatus VARCHAR(50), -- INITIATED, UPLOADED, NOTIFICATION_RECEIVED, PROCESSED, FAILED
    NotificationStatus VARCHAR(50),
    FeedbackCount INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BatchRunErrors (
    ErrorID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BatchID BIGINT,
    RecordID VARCHAR(100),
    ErrorCode VARCHAR(50),
    ErrorMessage TEXT,
    FOREIGN KEY (BatchID) REFERENCES BatchRuns(BatchID)
);

CREATE TABLE IF NOT EXISTS BatchFeedbackResults (
    ResultID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BatchID BIGINT,
    RecordID VARCHAR(100),
    MatchID VARCHAR(100),
    MatchName TEXT, -- encrypted (PiiCryptoService); widened from VARCHAR(255) to hold ciphertext
    MatchScore VARCHAR(50),
    Status VARCHAR(50),
    FOREIGN KEY (BatchID) REFERENCES BatchRuns(BatchID)
);

CREATE TABLE IF NOT EXISTS MappingConfigs (
    MappingID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TargetPath VARCHAR(255) NOT NULL,
    SourceField VARCHAR(255),
    DefaultValue VARCHAR(255),
    Transformation VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MappingConfigSnapshots (
    SnapshotID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VersionLabel VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR(50) DEFAULT 'SYSTEM',
    Source VARCHAR(20) DEFAULT 'MANUAL',
    ConfigJson TEXT NOT NULL
);

ALTER TABLE BatchRuns ADD COLUMN IF NOT EXISTS MappingSnapshotID BIGINT;
ALTER TABLE BatchRuns ADD COLUMN IF NOT EXISTS ClientCount INT;

-- NRTS integration columns
ALTER TABLE ScreeningLogs ADD COLUMN IF NOT EXISTS NrtsProcessId BIGINT;
ALTER TABLE ScreeningResults ADD COLUMN IF NOT EXISTS NrtsReqId BIGINT;
ALTER TABLE ScreeningLogs ADD COLUMN IF NOT EXISTS FinalizedAt TIMESTAMP;

-- Append-only audit trail of every real request/response exchanged with NRTS
-- (submit, status polls, alert details, document fetches). RequestPayload/ResponsePayload
-- are encrypted at the application layer (PiiCryptoService) before being stored here.
CREATE TABLE IF NOT EXISTS ScreeningNrtsInteractions (
    InteractionID      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ScreeningLogID     BIGINT, -- nullable: some calls (e.g. document fetch) have no reliable correlation key
    ClientID           BIGINT,
    ExternalRequestID  VARCHAR(100),
    NrtsProcessId      BIGINT,
    NrtsReqId          BIGINT,
    InteractionType    VARCHAR(30) NOT NULL, -- SUBMIT | STATUS_POLL | ALERT_DETAILS | DOCUMENT_FETCH
    HttpStatus         INT,
    RequestPayload     TEXT,                 -- encrypted
    ResponsePayload    TEXT,                 -- encrypted
    IsFinal            BOOLEAN DEFAULT FALSE,
    CreatedAt          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ScreeningLogID) REFERENCES ScreeningLogs(LogID)
);
CREATE INDEX IF NOT EXISTS idx_nrts_interactions_logid ON ScreeningNrtsInteractions(ScreeningLogID);
CREATE INDEX IF NOT EXISTS idx_nrts_interactions_processid ON ScreeningNrtsInteractions(NrtsProcessId);

-- Mass Screening: link individual BatchRuns to an overall run group
ALTER TABLE BatchRuns ADD COLUMN IF NOT EXISTS RunGroupId VARCHAR(64);

-- Mass Screening: tracks a single 700K-client run across all sub-batches
CREATE TABLE IF NOT EXISTS BatchScreeningRuns (
    Id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RunGroupId         VARCHAR(64) NOT NULL UNIQUE,
    FileName           VARCHAR(255),
    SystemId           VARCHAR(100),
    TotalClientCount   BIGINT,
    TotalBatches       INT,
    BatchesCompleted   INT DEFAULT 0,
    OverallStatus      VARCHAR(20) DEFAULT 'DETECTED',
    PersistClients     BOOLEAN DEFAULT FALSE,
    CallbackWebhookUrl VARCHAR(1000),
    ErrorMessage       TEXT,
    CreatedAt          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CompletedAt        TIMESTAMP
);

-- Mass Screening staging: full client data buffered for persist-first mode (Mode B)
-- PII columns (FirstName, MiddleName, LastName, NameAtBirth, NickName, DateOfBirth, IdNumber,
-- AddressLine1, PlaceOfBirth, CityOfBirth) are encrypted at the application layer
-- (PiiCryptoService) before being stored — widened to TEXT to hold ciphertext, and
-- DateOfBirth changed from DATE to TEXT since the encrypted value is no longer a SQL date.
CREATE TABLE IF NOT EXISTS BatchScreeningStaging (
    Id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RunGroupId             VARCHAR(64) NOT NULL,
    ClientId               BIGINT,
    TitlePrefix            VARCHAR(50),
    FirstName              TEXT,                 -- encrypted
    MiddleName             TEXT,                 -- encrypted
    LastName               TEXT,                 -- encrypted
    TitleSuffix            VARCHAR(50),
    Citizenship1           VARCHAR(100),
    Citizenship2           VARCHAR(100),
    OnboardingDate         DATE,
    Status                 VARCHAR(20),
    NameAtBirth            TEXT,                 -- encrypted
    NickName               TEXT,                 -- encrypted
    Gender                 VARCHAR(10),
    DateOfBirth            TEXT,                 -- encrypted (was DATE)
    Language               VARCHAR(50),
    Occupation             VARCHAR(255),
    CountryOfTax           VARCHAR(100),
    SourceOfFundsCountry   VARCHAR(100),
    FatcaStatus            VARCHAR(50),
    CrsStatus              VARCHAR(50),
    AddressLine1           TEXT,                 -- encrypted
    City                   VARCHAR(255),
    ZipCode                VARCHAR(50),
    Province               VARCHAR(255),
    Country                VARCHAR(100),
    Nationality            VARCHAR(100),
    LegDocType             VARCHAR(100),
    IdNumber               TEXT,                 -- encrypted
    PlaceOfBirth           TEXT,                 -- encrypted
    CityOfBirth            TEXT,                 -- encrypted
    CountryOfBirth         VARCHAR(100),
    ProcessingStatus       VARCHAR(20) DEFAULT 'PENDING',
    CreatedAt              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
