-- ============================================================
-- KYC Orchestration Service — Database Schema
-- Table: kyc_transaction_audit
-- Strategy: spring.sql.init.mode=always (matches all other services)
-- ============================================================

CREATE TABLE IF NOT EXISTS kyc_transaction_audit (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Core identity
    unique_client_id                VARCHAR(100),
    business_line                   VARCHAR(100),
    webhook_url                     VARCHAR(500),

    -- PII (stored encrypted via AES-256-GCM AttributeEncryptor)
    first_name                      TEXT,
    last_name                       TEXT,
    dob                             TEXT,

    -- Biographical / citizenship
    city_of_birth                   VARCHAR(100),
    country_of_birth                VARCHAR(100),
    primary_citizenship             VARCHAR(100),
    second_citizenship              VARCHAR(100),

    -- Residential address (line1/line2 encrypted)
    addr_line1                      TEXT,
    addr_line2                      TEXT,
    addr_city                       VARCHAR(100),
    addr_zip                        VARCHAR(20),
    country_of_residence            VARCHAR(100),
    occupation                      VARCHAR(100),

    -- Legitimisation document
    type_of_legitimization_document VARCHAR(100),
    issuing_authority               VARCHAR(100),
    identification_number           TEXT,       -- encrypted
    expiration_date                 VARCHAR(50),

    -- Tax identifier (encrypted)
    german_tax_id                   TEXT,

    -- Orchestration outcome
    kyc_status                      VARCHAR(50),
    screening_status                VARCHAR(50),
    screening_context               TEXT,       -- comma-separated list via StringListConverter
    risk_rating                     VARCHAR(50),

    -- External trace IDs
    viewer_user_id                  VARCHAR(100),
    screening_request_id            VARCHAR(100),
    risk_request_id                 VARCHAR(100),

    -- Latency telemetry
    screening_start_at              TIMESTAMP,
    screening_end_at                TIMESTAMP,
    risk_start_at                   TIMESTAMP,
    risk_end_at                     TIMESTAMP,

    -- Audit timestamps
    created_at                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_kyc_audit_unique_client_id ON kyc_transaction_audit(unique_client_id);

-- ============================================================
-- Append-only event/audit trail for one KYC transaction's lifecycle.
-- kyc_transaction_audit only tracks current state; this table records every
-- INITIATED / SCREENING_RESULT / RISK_RESULT / FINALIZED / STATUS_CHANGED event,
-- including the full raw downstream response (encrypted) that the audit row discards.
-- ============================================================

CREATE TABLE IF NOT EXISTS kyc_orchestration_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kyc_transaction_id   BIGINT NOT NULL,
    unique_client_id     VARCHAR(100),
    event_type           VARCHAR(30) NOT NULL, -- INITIATED | SCREENING_RESULT | RISK_RESULT | FINALIZED | STATUS_CHANGED
    old_status           VARCHAR(50),
    new_status           VARCHAR(50),
    source               VARCHAR(50),           -- screening-service | risk-service | nca-callback | system
    downstream_response  TEXT,                  -- encrypted via AttributeEncryptor; raw JSON where applicable
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (kyc_transaction_id) REFERENCES kyc_transaction_audit(id)
);
CREATE INDEX IF NOT EXISTS idx_kyc_events_transaction_id ON kyc_orchestration_events(kyc_transaction_id);
